### ISSUE TITLE
print to pdf doesn't work as expected

### ISSUE THREAD

**Issue by schwartztal** [JonClayton/Mastercraft-Lighting#94]
not sure exactly what's happening but on a new production with no channels, print button displayed a pdf with lots of info (guessing this is a pdf of another show?)

![image](https://cloud.githubusercontent.com/assets/14220049/12737234/9b002eca-c90b-11e5-80f3-5fcb6448e138.png)

**Comment by schwartztal** [comment]
Also the case for a non-empty production, returns the pdf embedded above.

**Comment by mtyzz** [comment]
This was lazy routing on my part; I think I fixed it but I won't know until the routing changes get migrated.

**Comment by mtyzz** [comment]
Fixed!
